version: 0.1
phases:    
    install:        
        commands:            
            - 'touch .npmignore'              
    pre_build:        
        commands:            
            - 'npm install'
            - 'nvm use 18'
    build:        
        commands:            
            - 'npm run build'    
